export const SET_DATA_CATEGORY = "SET_DATA_CATEGORY";
export const SET_DATA_PRODUCT = "SET_DATA_PRODUCT";
export const FILTER_PRODUCT_BY_STAR = "FILTER_PRODUCT_BY_STAR";
export const FILTER_PRODUCT_BY_COLOR = "FILTER_PRODUCT_BY_COLOR";
export const CLEAR_FILTER_PRODUCT = "CLEAR_FILTER_PRODUCT";

export const FILTER_PRICE = "FILTER_PRICE";
export const CLEAR_FILTER_PRICE = "CLEAR_FILTER_PRICE";
